hydra:
  run:
    dir: /home/shibutani/fs/ASR/projects/template/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

train:
  cuda: 0
  num_epoch: 40
  num_batch: 8
  lr: 0.0001
  weight_decay: 0.005
  warmup_epochs: 1000