hydra:
  run:
    dir: /home/shibutani/fs/ASR/projects/subsetselection-rep/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset: TIMIT

selection:
  method: cowerage
  wer_calc_total_run: 10
  wer_calc_epoch: 26
  retain: 0.4

train:
  cuda: 0
  epoch: 40
  batch: 8
  lr: 0.0001
  weight_decay: 0.005
  warmup_epochs: 1000
