hydra:
  run:
    dir: /home/shibutani/fs/ASR/projects/adaptive-noise-reduction/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset:
  name: "CSJ"
  train:
    json_file_path: "./json/vad/noisy_pretrain_with_subsampled_vad.json"
  eval:
    json_file_path: "./json/vad/noisy_pretrain_eval_with_subsampled_vad.json"
  eval_ref:
    json_file_path: "./json/vad/noisy_pretrain_eval_ref_with_subsampled_vad.json"

tokenizer:
  model_file_path: "./vocabs/csj_train_nodup_sp_4096.bpe.model"

model:
  name:
    "CausalConformerMultitaskCTCLLAdapterModel"
  base_model_path: "./artifacts/ctc_pretrain/d6d8d760048d46acbe285036d6be9f52/artifacts/model_20.pth"
  adapter_weight: 0.5
  spec_aug:
    num_freq_mask: 2
    freq_mask_max_length: 30
    num_time_mask: 2
    time_mask_max_length: 40

decoder:
  type: "greedy"

train:
  num_epoch: 5
  batch_sec: 3000
  batch_text_len: 10000
  accum_sec: 3000
  optimize:
    lr: 0.0005
    weight_decay: 0.000001
    eps: 0.000000001
    beta1: 0.9
    beta2: 0.98