hydra:
  run:
    dir: /home/shibutani/fs/ASR/projects/rnn-t-trial/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset:
  name: "Librispeech"
  dev_split: "dev-other"

model:
  encoder:
    input_size: 80
    subsampled_input_size: 144
    num_conformer_blocks: 16
    ff_hidden_size: 144
    conv_hidden_size: 144
    conv_kernel_size: 16 # non-causalの半分
    mha_num_heads: 4
    dropout: 0.1
    subsampling_kernel_size1: 3
    subsampling_stride1: 2
    subsampling_kernel_size2: 3
    subsampling_stride2: 2
    num_previous_frames: "all"
  predictor:
    embedding_size: 320
    hidden_size: 320
    num_layers: 1
  jointnet:
    hidden_size: 320
  spec_aug:
    num_freq_mask: 2
    freq_mask_max_length: 30
    num_time_mask: 2
    time_mask_max_length: 40

decoder:
  type: "streaming_greedy"
  buffer_size: 4

train:
  num_epoch: 100
  batch_sec: 180
  accum_sec: 1
  optimize:
    lr: 5
    warmup_steps: 10000
    weight_decay: 0.000001
    eps: 0.000000001
    beta1: 0.9
    beta2: 0.98