hydra:
  run:
    dir: /home/shibutani/fs/ASR/projects/template/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset:
  name: "LibriLight"

model:
  encoder:
    input_size: 80
    hidden_size: 512
    num_layers: 3
    output_size: 512
  predictor:
    embedding_size: 256
    hidden_size: 256
    num_layers: 3
    output_size: 256
  jointnet:
    hidden_size: 256

train:
  num_epoch: 100
  num_batch: 1
  accum_step: 4
  lr: 0.0001
  weight_decay: 0.0001