hydra:
  run:
    dir: /home/shibutani/fs/ASR/projects/template/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset:
  name: "LibriLight"

model:
  encoder:
    input_size: 80
    subsampled_input_size: 512
    num_conformer_blocks: 3
    ff_hidden_size: 1024
    conv_hidden_size: 512
    conv_kernel_size: 16
    mha_num_heads: 8
    dropout: 0.1
    subsampling_kernel_size1: 3
    subsampling_stride1: 2
    subsampling_kernel_size2: 3
    subsampling_stride2: 2
    num_previous_frames: 50
  predictor:
    embedding_size: 512
    hidden_size: 512
    num_layers: 3
  jointnet:
    hidden_size: 512
  spec_aug:
    num_freq_mask: 2
    freq_mask_max_length: 30
    num_time_mask: 2
    time_mask_max_length: 40

train:
  num_epoch: 50
  num_batch: 4
  accum_step: 1
  lr: 0.0001
  weight_decay: 0.0001