hydra:
  run:
    dir: /home/shibutani/fs/ASR/projects/template/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset:
  name: "LibriLight"

model:
  encoder:
    input_size: 80
    hidden_size: 512
    num_layers: 3
  predictor:
    embedding_size: 512
    hidden_size: 512
    num_layers: 3
  jointnet:
    hidden_size: 512

train:
  num_epoch: 50
  num_batch: 4
  accum_step: 1
  lr: 0.0001
  weight_decay: 0.0001