hydra:
  run:
    dir: /home/shibutani/fs/ASR/projects/rnn-t-trial/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset:
  name: "YesNo"

model:
  encoder:
    input_size: 40
    subsampled_input_size: 128
    num_conformer_blocks: 1
    ff_hidden_size: 128
    conv_hidden_size: 128
    conv_kernel_size: 16
    mha_num_heads: 4
    dropout: 0.1
    subsampling_kernel_size1: 3
    subsampling_stride1: 2
    subsampling_kernel_size2: 3
    subsampling_stride2: 2
    num_previous_frames: "all"
  predictor:
    embedding_size: 64
    hidden_size: 64
    num_layers: 1
  jointnet:
    hidden_size: 64
  spec_aug:
    num_freq_mask: 2
    freq_mask_max_length: 30
    num_time_mask: 2
    time_mask_max_length: 40

decoder:
  type: "streaming_greedy"
  buffer_size: 4

train:
  num_epoch: 100
  batch_sec: 100
  accum_sec: 1
  optimize:
    warmup_steps: 25000
    lr: 5.0
    weight_decay: 0.0001
    eps: 0.000000001
    beta1: 0.9
    beta2: 0.98