hydra:
  run:
    dir: /home/shibutani/fs/ASR/projects/template/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset:
  name: "YesNo"

model:
  encoder:
    input_size: 40
    subsampled_input_size: 32
    hidden_size: 64
    num_layers: 1
    output_size: 64
  predictor:
    embedding_size: 64
    hidden_size: 64
    num_layers: 1
    output_size: 64
  jointnet:
    hidden_size: 64

train:
  num_epoch: 100
  num_batch: 2
  accum_step: 1
  lr: 0.0005
  weight_decay: 0.0001